###

GET http://localhost:3000/api/users

###

GET http://localhost:3000

###

POST http://localhost:3000/api/users/new
Content-Type: application/json

{
  "name": "Jill",
  "town": "Taurage",
  "age": 33
}

###

DELETE  http://localhost:3003/api/posts/62429bc6f94300d1b8a1c8f1
###

GET  http://localhost:3003/api/posts/6243ec9e13e9b6637f4c703c

###

GET https://one-more-mca.herokuapp.com/api/posts

###

PUT https://one-more-mca.herokuapp.com/api/posts/6242cabbc0956cf9e4000d2d
Content-Type: application/json

{
  "title": "Post about JS edited",
  "author": "James",
  "body": "Body of post About JS",
  "year": 2015
}

####
POST https://one-more-mca.herokuapp.com/api/posts
Content-Type: application/json

{
  "title": "Post about JS",
  "author": "James",
  "body": "Body of post About JS",
  "year": 2005
}

####

POST https://radial-reinvented-shoe.glitch.me
Content-Type: application/json

{
  "title": "asdasdasd",
  "author": "Jills",
  "body": "Body of post 1",
  "year": 2000
}