###

GET http://localhost:3000/api/users

###

GET http://localhost:3000

###

POST http://localhost:3000/api/users/new
Content-Type: application/json

{
  "name": "Jill",
  "town": "Taurage",
  "age": 33
}

###

DELETE  http://localhost:3003/api/posts/62429bc6f94300d1b8a1c8f1

###

GET https://one-more-mca.herokuapp.com/api/posts
###

PUT http://localhost:3003/api/posts/62416561f0048a09af8b471b
Content-Type: application/json

{
  "title": "Post 1 Edited",
  "author": "Jills",
  "body": "Body of post 1",
  "year": 1990
}

####
POST https://one-more-mca.herokuapp.com/api/posts
Content-Type: application/json

{
  "title": "Post about JS",
  "author": "James",
  "body": "Body of post About JS",
  "year": 2005
}

####

POST https://radial-reinvented-shoe.glitch.me
Content-Type: application/json

{
  "title": "asdasdasd",
  "author": "Jills",
  "body": "Body of post 1",
  "year": 2000
}